version: "2"

services:
    db:
        image: mongo
        expose:
            - "27017"
        volumes: 
            - mongodata:/mongo-data/db
    web:
        build: .
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes: 
            - .:/src/
            - /node_modules
volumes: 
    mongodata: