version: "2"

services:
    db:
        image: mongo
        expose:
            - "27017"
        volumes: 
            - ./mongo-data/db/seed.js:/docker-entrypoint-initdb.d/seed.js
            - mongodata:/data/db
            - ./run.sh:/run.sh
        command: bash -c "
            chmod +x ./run.sh
            run ./run.sh "
    web:
        build: .
        depends_on:
            - db
        ports:
            - "8000:8000"
        volumes: 
            - .:/src/
            - /node_modules
volumes: 
  mongodata: