name: Deploy back-end
  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
        needs: ci
    
      steps:
      - name: Checkout files
        uses: actions/checkout@v2
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN }}
