name: Build back-end
on: push

jobs:
  build-app:
    name: Run back-end
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v2.4.0

      - name: Instalar Node
        uses: actions/setup-node@v1 
        with:
          node-version: '14.18.1'

      - name: Instalar dependencias
        run: npm install    
        
      - name: test
        run: |
         npm run test