name: Build front-end
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Run back-end
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v2.4.0

      - name: Instalar Node
        uses: actions/setup-node@v1 
        with:
          node-version: '14.18.1'

      - name: Instalar dependencias
        run: npm install    
        
      - name: test
        run: npm run test
    
  deploy: 
    needs: build
      
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            
      