name: Backend podbuster
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  jobs:
    build:
      name: Run back-end
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repositorio
          uses: actions/checkout@v2.4.0

        - name: Instalar Node
          uses: actions/setup-node@2.4.0 
          with:
            node-version: '14.18.1'

        - name: Instalar dependencias
          run: npm install    
          
        - name: test
          run: |
          npm run test
name: Deploy back-end
  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      name: Deploy
      runs-on: ubuntu-latest
        needs: ci
    
      steps:
      - name: Checkout files
        uses: actions/checkout@v2
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN }}
