name: Build and Deploy back-end
on:
  push:
    #branches: [main]
  #pull_request:
    #branches: [main]
env:
  REGISTRY: "registry.digitalocean.com/podbuster"
  IMAGE_NAME: "podcast-library-backend_web"
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          command: |
            touch hola.txt